# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(130, 290, 16, 201))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(160, 290, 321, 201))
        self.widget.setObjectName("widget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 270, 451, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 290, 85, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbtn_fota = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn_fota.setObjectName("rbtn_fota")
        self.verticalLayout.addWidget(self.rbtn_fota)
        self.rbtn_pushFile = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn_pushFile.setObjectName("rbtn_pushFile")
        self.verticalLayout.addWidget(self.rbtn_pushFile)
        self.rbtn_installAPk = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn_installAPk.setObjectName("rbtn_installAPk")
        self.verticalLayout.addWidget(self.rbtn_installAPk)
        self.rbtn_mute = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn_mute.setObjectName("rbtn_mute")
        self.verticalLayout.addWidget(self.rbtn_mute)
        self.rbtn_edlMode = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn_edlMode.setObjectName("rbtn_edlMode")
        self.verticalLayout.addWidget(self.rbtn_edlMode)
        self.rbtn_userdefine = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn_userdefine.setObjectName("rbtn_userdefine")
        self.verticalLayout.addWidget(self.rbtn_userdefine)
        self.rbtn_monkeyPreset = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn_monkeyPreset.setObjectName("rbtn_monkeyPreset")
        self.verticalLayout.addWidget(self.rbtn_monkeyPreset)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 451, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 3)
        self.btn_lockDev = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_lockDev.setObjectName("btn_lockDev")
        self.gridLayout.addWidget(self.btn_lockDev, 0, 1, 1, 1)
        self.btn_flashDev = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_flashDev.setObjectName("btn_flashDev")
        self.gridLayout.addWidget(self.btn_flashDev, 0, 0, 1, 1)
        self.btn_run = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_run.setObjectName("btn_run")
        self.gridLayout.addWidget(self.btn_run, 0, 2, 1, 1)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_flashDev.clicked.connect(MainWindow.flashDev)
        self.btn_lockDev.clicked.connect(MainWindow.lockDev)
        self.btn_run.clicked.connect(MainWindow.run)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rbtn_fota.setText(_translate("MainWindow", "FOTA测试"))
        self.rbtn_pushFile.setText(_translate("MainWindow", "传输文件"))
        self.rbtn_installAPk.setText(_translate("MainWindow", "安装应用"))
        self.rbtn_mute.setText(_translate("MainWindow", "静音"))
        self.rbtn_edlMode.setText(_translate("MainWindow", "重启"))
        self.rbtn_userdefine.setText(_translate("MainWindow", "自定义"))
        self.rbtn_monkeyPreset.setText(_translate("MainWindow", "Monkey文件"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DeviceID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Progress"))
        self.btn_lockDev.setText(_translate("MainWindow", "锁定设备"))
        self.btn_flashDev.setText(_translate("MainWindow", "刷新设备"))
        self.btn_run.setText(_translate("MainWindow", "执行"))
