settings put system screen_off_timeout 1
pm grant com.android.chrome android.permission.READ_CONTACTS
pm grant com.android.chrome android.permission.WRITE_CONTACTS
pm grant com.android.chrome android.permission.GET_ACCOUNTS
pm grant com.android.chrome android.permission.READ_PHONE_STATE
pm grant com.android.chrome android.permission.CALL_PHONE
pm grant com.android.chrome android.permission.READ_CALENDAR
pm grant com.android.chrome android.permission.WRITE_CALENDAR
pm grant com.android.chrome android.permission.READ_CALL_LOG
pm grant com.android.chrome android.permission.WRITE_CALL_LOG
pm grant com.android.chrome android.permission.CAMERA
pm grant com.android.chrome android.permission.ACCESS_FINE_LOCATION
pm grant com.android.chrome android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.chrome android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.RECORD_AUDIO
pm grant com.android.chrome android.permission.READ_SMS
pm grant com.android.deskclock android.permission.READ_CONTACTS
pm grant com.android.deskclock android.permission.WRITE_CONTACTS
pm grant com.android.deskclock android.permission.GET_ACCOUNTS
pm grant com.android.deskclock android.permission.READ_PHONE_STATE
pm grant com.android.deskclock android.permission.CALL_PHONE
pm grant com.android.deskclock android.permission.READ_CALENDAR
pm grant com.android.deskclock android.permission.WRITE_CALENDAR
pm grant com.android.deskclock android.permission.READ_CALL_LOG
pm grant com.android.deskclock android.permission.WRITE_CALL_LOG
pm grant com.android.deskclock android.permission.CAMERA
pm grant com.android.deskclock android.permission.ACCESS_FINE_LOCATION
pm grant com.android.deskclock android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.deskclock android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.deskclock android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.deskclock android.permission.RECORD_AUDIO
pm grant com.android.deskclock android.permission.READ_SMS
pm grant com.android.settings android.permission.READ_CONTACTS
pm grant com.android.settings android.permission.WRITE_CONTACTS
pm grant com.android.settings android.permission.GET_ACCOUNTS
pm grant com.android.settings android.permission.READ_PHONE_STATE
pm grant com.android.settings android.permission.CALL_PHONE
pm grant com.android.settings android.permission.READ_CALENDAR
pm grant com.android.settings android.permission.WRITE_CALENDAR
pm grant com.android.settings android.permission.READ_CALL_LOG
pm grant com.android.settings android.permission.WRITE_CALL_LOG
pm grant com.android.settings android.permission.CAMERA
pm grant com.android.settings android.permission.ACCESS_FINE_LOCATION
pm grant com.android.settings android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.settings android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.settings android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.settings android.permission.RECORD_AUDIO
pm grant com.android.settings android.permission.READ_SMS
pm grant com.android.vending android.permission.READ_CONTACTS
pm grant com.android.vending android.permission.WRITE_CONTACTS
pm grant com.android.vending android.permission.GET_ACCOUNTS
pm grant com.android.vending android.permission.READ_PHONE_STATE
pm grant com.android.vending android.permission.CALL_PHONE
pm grant com.android.vending android.permission.READ_CALENDAR
pm grant com.android.vending android.permission.WRITE_CALENDAR
pm grant com.android.vending android.permission.READ_CALL_LOG
pm grant com.android.vending android.permission.WRITE_CALL_LOG
pm grant com.android.vending android.permission.CAMERA
pm grant com.android.vending android.permission.ACCESS_FINE_LOCATION
pm grant com.android.vending android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.vending android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.vending android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.vending android.permission.RECORD_AUDIO
pm grant com.android.vending android.permission.READ_SMS
pm grant com.google.android.apps.assistant android.permission.READ_CONTACTS
pm grant com.google.android.apps.assistant android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.assistant android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.assistant android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.assistant android.permission.CALL_PHONE
pm grant com.google.android.apps.assistant android.permission.READ_CALENDAR
pm grant com.google.android.apps.assistant android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.assistant android.permission.READ_CALL_LOG
pm grant com.google.android.apps.assistant android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.assistant android.permission.CAMERA
pm grant com.google.android.apps.assistant android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.assistant android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.assistant android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.assistant android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.assistant android.permission.RECORD_AUDIO
pm grant com.google.android.apps.assistant android.permission.READ_SMS
pm grant com.google.android.apps.docs android.permission.READ_CONTACTS
pm grant com.google.android.apps.docs android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.docs android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.docs android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.docs android.permission.CALL_PHONE
pm grant com.google.android.apps.docs android.permission.READ_CALENDAR
pm grant com.google.android.apps.docs android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.docs android.permission.READ_CALL_LOG
pm grant com.google.android.apps.docs android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.docs android.permission.CAMERA
pm grant com.google.android.apps.docs android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.docs android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.docs android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.docs android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.docs android.permission.RECORD_AUDIO
pm grant com.google.android.apps.docs android.permission.READ_SMS
pm grant com.google.android.apps.maps android.permission.READ_CONTACTS
pm grant com.google.android.apps.maps android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.maps android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.maps android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.maps android.permission.CALL_PHONE
pm grant com.google.android.apps.maps android.permission.READ_CALENDAR
pm grant com.google.android.apps.maps android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.maps android.permission.READ_CALL_LOG
pm grant com.google.android.apps.maps android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.maps android.permission.CAMERA
pm grant com.google.android.apps.maps android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.maps android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.maps android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.maps android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.maps android.permission.RECORD_AUDIO
pm grant com.google.android.apps.maps android.permission.READ_SMS
pm grant com.google.android.apps.messaging android.permission.READ_CONTACTS
pm grant com.google.android.apps.messaging android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.messaging android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.messaging android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.messaging android.permission.CALL_PHONE
pm grant com.google.android.apps.messaging android.permission.READ_CALENDAR
pm grant com.google.android.apps.messaging android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.messaging android.permission.READ_CALL_LOG
pm grant com.google.android.apps.messaging android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.messaging android.permission.CAMERA
pm grant com.google.android.apps.messaging android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.messaging android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.messaging android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.messaging android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.messaging android.permission.RECORD_AUDIO
pm grant com.google.android.apps.messaging android.permission.READ_SMS
pm grant com.google.android.apps.photosgo android.permission.READ_CONTACTS
pm grant com.google.android.apps.photosgo android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.photosgo android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.photosgo android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.photosgo android.permission.CALL_PHONE
pm grant com.google.android.apps.photosgo android.permission.READ_CALENDAR
pm grant com.google.android.apps.photosgo android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.photosgo android.permission.READ_CALL_LOG
pm grant com.google.android.apps.photosgo android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.photosgo android.permission.CAMERA
pm grant com.google.android.apps.photosgo android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.photosgo android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.photosgo android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.photosgo android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.photosgo android.permission.RECORD_AUDIO
pm grant com.google.android.apps.photosgo android.permission.READ_SMS
pm grant com.google.android.apps.tachyon android.permission.READ_CONTACTS
pm grant com.google.android.apps.tachyon android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.tachyon android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.tachyon android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.tachyon android.permission.CALL_PHONE
pm grant com.google.android.apps.tachyon android.permission.READ_CALENDAR
pm grant com.google.android.apps.tachyon android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.tachyon android.permission.READ_CALL_LOG
pm grant com.google.android.apps.tachyon android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.tachyon android.permission.CAMERA
pm grant com.google.android.apps.tachyon android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.tachyon android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.tachyon android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.tachyon android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.tachyon android.permission.RECORD_AUDIO
pm grant com.google.android.apps.tachyon android.permission.READ_SMS
pm grant com.google.android.apps.youtube.music android.permission.READ_CONTACTS
pm grant com.google.android.apps.youtube.music android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.youtube.music android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.youtube.music android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.youtube.music android.permission.CALL_PHONE
pm grant com.google.android.apps.youtube.music android.permission.READ_CALENDAR
pm grant com.google.android.apps.youtube.music android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.youtube.music android.permission.READ_CALL_LOG
pm grant com.google.android.apps.youtube.music android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.youtube.music android.permission.CAMERA
pm grant com.google.android.apps.youtube.music android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.youtube.music android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.youtube.music android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.youtube.music android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.youtube.music android.permission.RECORD_AUDIO
pm grant com.google.android.apps.youtube.music android.permission.READ_SMS
pm grant com.google.android.calendar android.permission.READ_CONTACTS
pm grant com.google.android.calendar android.permission.WRITE_CONTACTS
pm grant com.google.android.calendar android.permission.GET_ACCOUNTS
pm grant com.google.android.calendar android.permission.READ_PHONE_STATE
pm grant com.google.android.calendar android.permission.CALL_PHONE
pm grant com.google.android.calendar android.permission.READ_CALENDAR
pm grant com.google.android.calendar android.permission.WRITE_CALENDAR
pm grant com.google.android.calendar android.permission.READ_CALL_LOG
pm grant com.google.android.calendar android.permission.WRITE_CALL_LOG
pm grant com.google.android.calendar android.permission.CAMERA
pm grant com.google.android.calendar android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.calendar android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.calendar android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.calendar android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.calendar android.permission.RECORD_AUDIO
pm grant com.google.android.calendar android.permission.READ_SMS
pm grant com.google.android.gm android.permission.READ_CONTACTS
pm grant com.google.android.gm android.permission.WRITE_CONTACTS
pm grant com.google.android.gm android.permission.GET_ACCOUNTS
pm grant com.google.android.gm android.permission.READ_PHONE_STATE
pm grant com.google.android.gm android.permission.CALL_PHONE
pm grant com.google.android.gm android.permission.READ_CALENDAR
pm grant com.google.android.gm android.permission.WRITE_CALENDAR
pm grant com.google.android.gm android.permission.READ_CALL_LOG
pm grant com.google.android.gm android.permission.WRITE_CALL_LOG
pm grant com.google.android.gm android.permission.CAMERA
pm grant com.google.android.gm android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.gm android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.gm android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.gm android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.gm android.permission.RECORD_AUDIO
pm grant com.google.android.gm android.permission.READ_SMS
pm grant com.google.android.youtube android.permission.READ_CONTACTS
pm grant com.google.android.youtube android.permission.WRITE_CONTACTS
pm grant com.google.android.youtube android.permission.GET_ACCOUNTS
pm grant com.google.android.youtube android.permission.READ_PHONE_STATE
pm grant com.google.android.youtube android.permission.CALL_PHONE
pm grant com.google.android.youtube android.permission.READ_CALENDAR
pm grant com.google.android.youtube android.permission.WRITE_CALENDAR
pm grant com.google.android.youtube android.permission.READ_CALL_LOG
pm grant com.google.android.youtube android.permission.WRITE_CALL_LOG
pm grant com.google.android.youtube android.permission.CAMERA
pm grant com.google.android.youtube android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.youtube android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.youtube android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.RECORD_AUDIO
pm grant com.google.android.youtube android.permission.READ_SMS
pm grant com.tcl.camera android.permission.READ_CONTACTS
pm grant com.tcl.camera android.permission.WRITE_CONTACTS
pm grant com.tcl.camera android.permission.GET_ACCOUNTS
pm grant com.tcl.camera android.permission.READ_PHONE_STATE
pm grant com.tcl.camera android.permission.CALL_PHONE
pm grant com.tcl.camera android.permission.READ_CALENDAR
pm grant com.tcl.camera android.permission.WRITE_CALENDAR
pm grant com.tcl.camera android.permission.READ_CALL_LOG
pm grant com.tcl.camera android.permission.WRITE_CALL_LOG
pm grant com.tcl.camera android.permission.CAMERA
pm grant com.tcl.camera android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.camera android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.camera android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.camera android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.camera android.permission.RECORD_AUDIO
pm grant com.tcl.camera android.permission.READ_SMS
pm grant com.tct.contacts.transfer android.permission.READ_CONTACTS
pm grant com.tct.contacts.transfer android.permission.WRITE_CONTACTS
pm grant com.tct.contacts.transfer android.permission.GET_ACCOUNTS
pm grant com.tct.contacts.transfer android.permission.READ_PHONE_STATE
pm grant com.tct.contacts.transfer android.permission.CALL_PHONE
pm grant com.tct.contacts.transfer android.permission.READ_CALENDAR
pm grant com.tct.contacts.transfer android.permission.WRITE_CALENDAR
pm grant com.tct.contacts.transfer android.permission.READ_CALL_LOG
pm grant com.tct.contacts.transfer android.permission.WRITE_CALL_LOG
pm grant com.tct.contacts.transfer android.permission.CAMERA
pm grant com.tct.contacts.transfer android.permission.ACCESS_FINE_LOCATION
pm grant com.tct.contacts.transfer android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.contacts.transfer android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.contacts.transfer android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tct.contacts.transfer android.permission.RECORD_AUDIO
pm grant com.tct.contacts.transfer android.permission.READ_SMS
pm grant com.tct.dialer android.permission.READ_CONTACTS
pm grant com.tct.dialer android.permission.WRITE_CONTACTS
pm grant com.tct.dialer android.permission.GET_ACCOUNTS
pm grant com.tct.dialer android.permission.READ_PHONE_STATE
pm grant com.tct.dialer android.permission.CALL_PHONE
pm grant com.tct.dialer android.permission.READ_CALENDAR
pm grant com.tct.dialer android.permission.WRITE_CALENDAR
pm grant com.tct.dialer android.permission.READ_CALL_LOG
pm grant com.tct.dialer android.permission.WRITE_CALL_LOG
pm grant com.tct.dialer android.permission.CAMERA
pm grant com.tct.dialer android.permission.ACCESS_FINE_LOCATION
pm grant com.tct.dialer android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.dialer android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.dialer android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tct.dialer android.permission.RECORD_AUDIO
pm grant com.tct.dialer android.permission.READ_SMS
pm grant com.tct.robust android.permission.READ_CONTACTS
pm grant com.tct.robust android.permission.WRITE_CONTACTS
pm grant com.tct.robust android.permission.GET_ACCOUNTS
pm grant com.tct.robust android.permission.READ_PHONE_STATE
pm grant com.tct.robust android.permission.CALL_PHONE
pm grant com.tct.robust android.permission.READ_CALENDAR
pm grant com.tct.robust android.permission.WRITE_CALENDAR
pm grant com.tct.robust android.permission.READ_CALL_LOG
pm grant com.tct.robust android.permission.WRITE_CALL_LOG
pm grant com.tct.robust android.permission.CAMERA
pm grant com.tct.robust android.permission.ACCESS_FINE_LOCATION
pm grant com.tct.robust android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.robust android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.robust android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tct.robust android.permission.RECORD_AUDIO
pm grant com.tct.robust android.permission.READ_SMS
pm grant com.google.android.apps.nbu.files android.permission.READ_CONTACTS
pm grant com.google.android.apps.nbu.files android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.nbu.files android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.nbu.files android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.nbu.files android.permission.CALL_PHONE
pm grant com.google.android.apps.nbu.files android.permission.READ_CALENDAR
pm grant com.google.android.apps.nbu.files android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.nbu.files android.permission.READ_CALL_LOG
pm grant com.google.android.apps.nbu.files android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.nbu.files android.permission.CAMERA
pm grant com.google.android.apps.nbu.files android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.nbu.files android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.nbu.files android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.nbu.files android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.nbu.files android.permission.RECORD_AUDIO
pm grant com.google.android.apps.nbu.files android.permission.READ_SMS
pm grant com.google.android.apps.searchlite android.permission.READ_CONTACTS
pm grant com.google.android.apps.searchlite android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.searchlite android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.searchlite android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.searchlite android.permission.CALL_PHONE
pm grant com.google.android.apps.searchlite android.permission.READ_CALENDAR
pm grant com.google.android.apps.searchlite android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.searchlite android.permission.READ_CALL_LOG
pm grant com.google.android.apps.searchlite android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.searchlite android.permission.CAMERA
pm grant com.google.android.apps.searchlite android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.searchlite android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.searchlite android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.searchlite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.searchlite android.permission.RECORD_AUDIO
pm grant com.google.android.apps.searchlite android.permission.READ_SMS
pm grant com.tcl.logger android.permission.READ_CONTACTS
pm grant com.tcl.logger android.permission.WRITE_CONTACTS
pm grant com.tcl.logger android.permission.GET_ACCOUNTS
pm grant com.tcl.logger android.permission.READ_PHONE_STATE
pm grant com.tcl.logger android.permission.CALL_PHONE
pm grant com.tcl.logger android.permission.READ_CALENDAR
pm grant com.tcl.logger android.permission.WRITE_CALENDAR
pm grant com.tcl.logger android.permission.READ_CALL_LOG
pm grant com.tcl.logger android.permission.WRITE_CALL_LOG
pm grant com.tcl.logger android.permission.CAMERA
pm grant com.tcl.logger android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.logger android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.logger android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.logger android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.logger android.permission.RECORD_AUDIO
pm grant com.tcl.logger android.permission.READ_SMS
pm grant com.tcl.usercare android.permission.READ_CONTACTS
pm grant com.tcl.usercare android.permission.WRITE_CONTACTS
pm grant com.tcl.usercare android.permission.GET_ACCOUNTS
pm grant com.tcl.usercare android.permission.READ_PHONE_STATE
pm grant com.tcl.usercare android.permission.CALL_PHONE
pm grant com.tcl.usercare android.permission.READ_CALENDAR
pm grant com.tcl.usercare android.permission.WRITE_CALENDAR
pm grant com.tcl.usercare android.permission.READ_CALL_LOG
pm grant com.tcl.usercare android.permission.WRITE_CALL_LOG
pm grant com.tcl.usercare android.permission.CAMERA
pm grant com.tcl.usercare android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.usercare android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.usercare android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.usercare android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.usercare android.permission.RECORD_AUDIO
pm grant com.tcl.usercare android.permission.READ_SMS
pm grant com.tct.onetouchbooster android.permission.READ_CONTACTS
pm grant com.tct.onetouchbooster android.permission.WRITE_CONTACTS
pm grant com.tct.onetouchbooster android.permission.GET_ACCOUNTS
pm grant com.tct.onetouchbooster android.permission.READ_PHONE_STATE
pm grant com.tct.onetouchbooster android.permission.CALL_PHONE
pm grant com.tct.onetouchbooster android.permission.READ_CALENDAR
pm grant com.tct.onetouchbooster android.permission.WRITE_CALENDAR
pm grant com.tct.onetouchbooster android.permission.READ_CALL_LOG
pm grant com.tct.onetouchbooster android.permission.WRITE_CALL_LOG
pm grant com.tct.onetouchbooster android.permission.CAMERA
pm grant com.tct.onetouchbooster android.permission.ACCESS_FINE_LOCATION
pm grant com.tct.onetouchbooster android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.onetouchbooster android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.onetouchbooster android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tct.onetouchbooster android.permission.RECORD_AUDIO
pm grant com.tct.onetouchbooster android.permission.READ_SMS
pm grant com.facebook.lite android.permission.READ_CONTACTS
pm grant com.facebook.lite android.permission.WRITE_CONTACTS
pm grant com.facebook.lite android.permission.GET_ACCOUNTS
pm grant com.facebook.lite android.permission.READ_PHONE_STATE
pm grant com.facebook.lite android.permission.CALL_PHONE
pm grant com.facebook.lite android.permission.READ_CALENDAR
pm grant com.facebook.lite android.permission.WRITE_CALENDAR
pm grant com.facebook.lite android.permission.READ_CALL_LOG
pm grant com.facebook.lite android.permission.WRITE_CALL_LOG
pm grant com.facebook.lite android.permission.CAMERA
pm grant com.facebook.lite android.permission.ACCESS_FINE_LOCATION
pm grant com.facebook.lite android.permission.ACCESS_COARSE_LOCATION
pm grant com.facebook.lite android.permission.READ_EXTERNAL_STORAGE
pm grant com.facebook.lite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.facebook.lite android.permission.RECORD_AUDIO
pm grant com.facebook.lite android.permission.READ_SMS
am start com.android.settings
