settings put system screen_off_timeout 1
setprop debug.print.log false
pm grant com.android.chrome android.permission.READ_CONTACTS
pm grant com.android.chrome android.permission.WRITE_CONTACTS
pm grant com.android.chrome android.permission.GET_ACCOUNTS
pm grant com.android.chrome android.permission.READ_PHONE_STATE
pm grant com.android.chrome android.permission.CALL_PHONE
pm grant com.android.chrome android.permission.READ_CALENDAR
pm grant com.android.chrome android.permission.WRITE_CALENDAR
pm grant com.android.chrome android.permission.READ_CALL_LOG
pm grant com.android.chrome android.permission.WRITE_CALL_LOG
pm grant com.android.chrome android.permission.CAMERA
pm grant com.android.chrome android.permission.ACCESS_FINE_LOCATION
pm grant com.android.chrome android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.chrome android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.RECORD_AUDIO
pm grant com.android.chrome android.permission.READ_SMS
pm grant com.android.settings android.permission.READ_CONTACTS
pm grant com.android.settings android.permission.WRITE_CONTACTS
pm grant com.android.settings android.permission.GET_ACCOUNTS
pm grant com.android.settings android.permission.READ_PHONE_STATE
pm grant com.android.settings android.permission.CALL_PHONE
pm grant com.android.settings android.permission.READ_CALENDAR
pm grant com.android.settings android.permission.WRITE_CALENDAR
pm grant com.android.settings android.permission.READ_CALL_LOG
pm grant com.android.settings android.permission.WRITE_CALL_LOG
pm grant com.android.settings android.permission.CAMERA
pm grant com.android.settings android.permission.ACCESS_FINE_LOCATION
pm grant com.android.settings android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.settings android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.settings android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.settings android.permission.RECORD_AUDIO
pm grant com.android.settings android.permission.READ_SMS
pm grant com.android.vending android.permission.READ_CONTACTS
pm grant com.android.vending android.permission.WRITE_CONTACTS
pm grant com.android.vending android.permission.GET_ACCOUNTS
pm grant com.android.vending android.permission.READ_PHONE_STATE
pm grant com.android.vending android.permission.CALL_PHONE
pm grant com.android.vending android.permission.READ_CALENDAR
pm grant com.android.vending android.permission.WRITE_CALENDAR
pm grant com.android.vending android.permission.READ_CALL_LOG
pm grant com.android.vending android.permission.WRITE_CALL_LOG
pm grant com.android.vending android.permission.CAMERA
pm grant com.android.vending android.permission.ACCESS_FINE_LOCATION
pm grant com.android.vending android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.vending android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.vending android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.vending android.permission.RECORD_AUDIO
pm grant com.android.vending android.permission.READ_SMS
pm grant com.google.android.apps.assistant android.permission.READ_CONTACTS
pm grant com.google.android.apps.assistant android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.assistant android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.assistant android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.assistant android.permission.CALL_PHONE
pm grant com.google.android.apps.assistant android.permission.READ_CALENDAR
pm grant com.google.android.apps.assistant android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.assistant android.permission.READ_CALL_LOG
pm grant com.google.android.apps.assistant android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.assistant android.permission.CAMERA
pm grant com.google.android.apps.assistant android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.assistant android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.assistant android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.assistant android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.assistant android.permission.RECORD_AUDIO
pm grant com.google.android.apps.assistant android.permission.READ_SMS
pm grant com.google.android.apps.messaging android.permission.READ_CONTACTS
pm grant com.google.android.apps.messaging android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.messaging android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.messaging android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.messaging android.permission.CALL_PHONE
pm grant com.google.android.apps.messaging android.permission.READ_CALENDAR
pm grant com.google.android.apps.messaging android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.messaging android.permission.READ_CALL_LOG
pm grant com.google.android.apps.messaging android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.messaging android.permission.CAMERA
pm grant com.google.android.apps.messaging android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.messaging android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.messaging android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.messaging android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.messaging android.permission.RECORD_AUDIO
pm grant com.google.android.apps.messaging android.permission.READ_SMS
pm grant com.google.android.apps.youtube.mango android.permission.READ_CONTACTS
pm grant com.google.android.apps.youtube.mango android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.youtube.mango android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.youtube.mango android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.youtube.mango android.permission.CALL_PHONE
pm grant com.google.android.apps.youtube.mango android.permission.READ_CALENDAR
pm grant com.google.android.apps.youtube.mango android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.youtube.mango android.permission.READ_CALL_LOG
pm grant com.google.android.apps.youtube.mango android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.youtube.mango android.permission.CAMERA
pm grant com.google.android.apps.youtube.mango android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.youtube.mango android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.youtube.mango android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.youtube.mango android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.youtube.mango android.permission.RECORD_AUDIO
pm grant com.google.android.apps.youtube.mango android.permission.READ_SMS
pm grant com.google.android.calendar android.permission.READ_CONTACTS
pm grant com.google.android.calendar android.permission.WRITE_CONTACTS
pm grant com.google.android.calendar android.permission.GET_ACCOUNTS
pm grant com.google.android.calendar android.permission.READ_PHONE_STATE
pm grant com.google.android.calendar android.permission.CALL_PHONE
pm grant com.google.android.calendar android.permission.READ_CALENDAR
pm grant com.google.android.calendar android.permission.WRITE_CALENDAR
pm grant com.google.android.calendar android.permission.READ_CALL_LOG
pm grant com.google.android.calendar android.permission.WRITE_CALL_LOG
pm grant com.google.android.calendar android.permission.CAMERA
pm grant com.google.android.calendar android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.calendar android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.calendar android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.calendar android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.calendar android.permission.RECORD_AUDIO
pm grant com.google.android.calendar android.permission.READ_SMS
pm grant com.google.android.deskclock android.permission.READ_CONTACTS
pm grant com.google.android.deskclock android.permission.WRITE_CONTACTS
pm grant com.google.android.deskclock android.permission.GET_ACCOUNTS
pm grant com.google.android.deskclock android.permission.READ_PHONE_STATE
pm grant com.google.android.deskclock android.permission.CALL_PHONE
pm grant com.google.android.deskclock android.permission.READ_CALENDAR
pm grant com.google.android.deskclock android.permission.WRITE_CALENDAR
pm grant com.google.android.deskclock android.permission.READ_CALL_LOG
pm grant com.google.android.deskclock android.permission.WRITE_CALL_LOG
pm grant com.google.android.deskclock android.permission.CAMERA
pm grant com.google.android.deskclock android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.deskclock android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.deskclock android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.deskclock android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.deskclock android.permission.RECORD_AUDIO
pm grant com.google.android.deskclock android.permission.READ_SMS
pm grant com.google.android.gm.lite android.permission.READ_CONTACTS
pm grant com.google.android.gm.lite android.permission.WRITE_CONTACTS
pm grant com.google.android.gm.lite android.permission.GET_ACCOUNTS
pm grant com.google.android.gm.lite android.permission.READ_PHONE_STATE
pm grant com.google.android.gm.lite android.permission.CALL_PHONE
pm grant com.google.android.gm.lite android.permission.READ_CALENDAR
pm grant com.google.android.gm.lite android.permission.WRITE_CALENDAR
pm grant com.google.android.gm.lite android.permission.READ_CALL_LOG
pm grant com.google.android.gm.lite android.permission.WRITE_CALL_LOG
pm grant com.google.android.gm.lite android.permission.CAMERA
pm grant com.google.android.gm.lite android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.gm.lite android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.gm.lite android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.gm.lite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.gm.lite android.permission.RECORD_AUDIO
pm grant com.google.android.gm.lite android.permission.READ_SMS
pm grant com.google.android.music android.permission.READ_CONTACTS
pm grant com.google.android.music android.permission.WRITE_CONTACTS
pm grant com.google.android.music android.permission.GET_ACCOUNTS
pm grant com.google.android.music android.permission.READ_PHONE_STATE
pm grant com.google.android.music android.permission.CALL_PHONE
pm grant com.google.android.music android.permission.READ_CALENDAR
pm grant com.google.android.music android.permission.WRITE_CALENDAR
pm grant com.google.android.music android.permission.READ_CALL_LOG
pm grant com.google.android.music android.permission.WRITE_CALL_LOG
pm grant com.google.android.music android.permission.CAMERA
pm grant com.google.android.music android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.music android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.music android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.music android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.music android.permission.RECORD_AUDIO
pm grant com.google.android.music android.permission.READ_SMS
pm grant com.mediatek.hz.camera android.permission.READ_CONTACTS
pm grant com.mediatek.hz.camera android.permission.WRITE_CONTACTS
pm grant com.mediatek.hz.camera android.permission.GET_ACCOUNTS
pm grant com.mediatek.hz.camera android.permission.READ_PHONE_STATE
pm grant com.mediatek.hz.camera android.permission.CALL_PHONE
pm grant com.mediatek.hz.camera android.permission.READ_CALENDAR
pm grant com.mediatek.hz.camera android.permission.WRITE_CALENDAR
pm grant com.mediatek.hz.camera android.permission.READ_CALL_LOG
pm grant com.mediatek.hz.camera android.permission.WRITE_CALL_LOG
pm grant com.mediatek.hz.camera android.permission.CAMERA
pm grant com.mediatek.hz.camera android.permission.ACCESS_FINE_LOCATION
pm grant com.mediatek.hz.camera android.permission.ACCESS_COARSE_LOCATION
pm grant com.mediatek.hz.camera android.permission.READ_EXTERNAL_STORAGE
pm grant com.mediatek.hz.camera android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.mediatek.hz.camera android.permission.RECORD_AUDIO
pm grant com.mediatek.hz.camera android.permission.READ_SMS
pm grant com.tcl.soundrecorder android.permission.READ_CONTACTS
pm grant com.tcl.soundrecorder android.permission.WRITE_CONTACTS
pm grant com.tcl.soundrecorder android.permission.GET_ACCOUNTS
pm grant com.tcl.soundrecorder android.permission.READ_PHONE_STATE
pm grant com.tcl.soundrecorder android.permission.CALL_PHONE
pm grant com.tcl.soundrecorder android.permission.READ_CALENDAR
pm grant com.tcl.soundrecorder android.permission.WRITE_CALENDAR
pm grant com.tcl.soundrecorder android.permission.READ_CALL_LOG
pm grant com.tcl.soundrecorder android.permission.WRITE_CALL_LOG
pm grant com.tcl.soundrecorder android.permission.CAMERA
pm grant com.tcl.soundrecorder android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.soundrecorder android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.soundrecorder android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.soundrecorder android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.soundrecorder android.permission.RECORD_AUDIO
pm grant com.tcl.soundrecorder android.permission.READ_SMS
pm grant com.tct.contacts android.permission.READ_CONTACTS
pm grant com.tct.contacts android.permission.WRITE_CONTACTS
pm grant com.tct.contacts android.permission.GET_ACCOUNTS
pm grant com.tct.contacts android.permission.READ_PHONE_STATE
pm grant com.tct.contacts android.permission.CALL_PHONE
pm grant com.tct.contacts android.permission.READ_CALENDAR
pm grant com.tct.contacts android.permission.WRITE_CALENDAR
pm grant com.tct.contacts android.permission.READ_CALL_LOG
pm grant com.tct.contacts android.permission.WRITE_CALL_LOG
pm grant com.tct.contacts android.permission.CAMERA
pm grant com.tct.contacts android.permission.ACCESS_FINE_LOCATION
pm grant com.tct.contacts android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.contacts android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.contacts android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tct.contacts android.permission.RECORD_AUDIO
pm grant com.tct.contacts android.permission.READ_SMS
pm grant com.tct.dialer android.permission.READ_CONTACTS
pm grant com.tct.dialer android.permission.WRITE_CONTACTS
pm grant com.tct.dialer android.permission.GET_ACCOUNTS
pm grant com.tct.dialer android.permission.READ_PHONE_STATE
pm grant com.tct.dialer android.permission.CALL_PHONE
pm grant com.tct.dialer android.permission.READ_CALENDAR
pm grant com.tct.dialer android.permission.WRITE_CALENDAR
pm grant com.tct.dialer android.permission.READ_CALL_LOG
pm grant com.tct.dialer android.permission.WRITE_CALL_LOG
pm grant com.tct.dialer android.permission.CAMERA
pm grant com.tct.dialer android.permission.ACCESS_FINE_LOCATION
pm grant com.tct.dialer android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.dialer android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.dialer android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tct.dialer android.permission.RECORD_AUDIO
pm grant com.tct.dialer android.permission.READ_SMS
pm grant com.android.documentsui android.permission.READ_CONTACTS
pm grant com.android.documentsui android.permission.WRITE_CONTACTS
pm grant com.android.documentsui android.permission.GET_ACCOUNTS
pm grant com.android.documentsui android.permission.READ_PHONE_STATE
pm grant com.android.documentsui android.permission.CALL_PHONE
pm grant com.android.documentsui android.permission.READ_CALENDAR
pm grant com.android.documentsui android.permission.WRITE_CALENDAR
pm grant com.android.documentsui android.permission.READ_CALL_LOG
pm grant com.android.documentsui android.permission.WRITE_CALL_LOG
pm grant com.android.documentsui android.permission.CAMERA
pm grant com.android.documentsui android.permission.ACCESS_FINE_LOCATION
pm grant com.android.documentsui android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.documentsui android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.documentsui android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.documentsui android.permission.RECORD_AUDIO
pm grant com.android.documentsui android.permission.READ_SMS
pm grant com.android.stk android.permission.READ_CONTACTS
pm grant com.android.stk android.permission.WRITE_CONTACTS
pm grant com.android.stk android.permission.GET_ACCOUNTS
pm grant com.android.stk android.permission.READ_PHONE_STATE
pm grant com.android.stk android.permission.CALL_PHONE
pm grant com.android.stk android.permission.READ_CALENDAR
pm grant com.android.stk android.permission.WRITE_CALENDAR
pm grant com.android.stk android.permission.READ_CALL_LOG
pm grant com.android.stk android.permission.WRITE_CALL_LOG
pm grant com.android.stk android.permission.CAMERA
pm grant com.android.stk android.permission.ACCESS_FINE_LOCATION
pm grant com.android.stk android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.stk android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.stk android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.stk android.permission.RECORD_AUDIO
pm grant com.android.stk android.permission.READ_SMS
pm grant com.google.android.apps.mapslite android.permission.READ_CONTACTS
pm grant com.google.android.apps.mapslite android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.mapslite android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.mapslite android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.mapslite android.permission.CALL_PHONE
pm grant com.google.android.apps.mapslite android.permission.READ_CALENDAR
pm grant com.google.android.apps.mapslite android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.mapslite android.permission.READ_CALL_LOG
pm grant com.google.android.apps.mapslite android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.mapslite android.permission.CAMERA
pm grant com.google.android.apps.mapslite android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.mapslite android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.mapslite android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.mapslite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.mapslite android.permission.RECORD_AUDIO
pm grant com.google.android.apps.mapslite android.permission.READ_SMS
pm grant com.google.android.apps.nbu.files android.permission.READ_CONTACTS
pm grant com.google.android.apps.nbu.files android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.nbu.files android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.nbu.files android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.nbu.files android.permission.CALL_PHONE
pm grant com.google.android.apps.nbu.files android.permission.READ_CALENDAR
pm grant com.google.android.apps.nbu.files android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.nbu.files android.permission.READ_CALL_LOG
pm grant com.google.android.apps.nbu.files android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.nbu.files android.permission.CAMERA
pm grant com.google.android.apps.nbu.files android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.nbu.files android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.nbu.files android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.nbu.files android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.nbu.files android.permission.RECORD_AUDIO
pm grant com.google.android.apps.nbu.files android.permission.READ_SMS
pm grant com.google.android.apps.searchlite android.permission.READ_CONTACTS
pm grant com.google.android.apps.searchlite android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.searchlite android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.searchlite android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.searchlite android.permission.CALL_PHONE
pm grant com.google.android.apps.searchlite android.permission.READ_CALENDAR
pm grant com.google.android.apps.searchlite android.permission.WRITE_CALENDAR
pm grant com.google.android.apps.searchlite android.permission.READ_CALL_LOG
pm grant com.google.android.apps.searchlite android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.searchlite android.permission.CAMERA
pm grant com.google.android.apps.searchlite android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.searchlite android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.searchlite android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.searchlite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.searchlite android.permission.RECORD_AUDIO
pm grant com.google.android.apps.searchlite android.permission.READ_SMS
pm grant com.tcl.calculator android.permission.READ_CONTACTS
pm grant com.tcl.calculator android.permission.WRITE_CONTACTS
pm grant com.tcl.calculator android.permission.GET_ACCOUNTS
pm grant com.tcl.calculator android.permission.READ_PHONE_STATE
pm grant com.tcl.calculator android.permission.CALL_PHONE
pm grant com.tcl.calculator android.permission.READ_CALENDAR
pm grant com.tcl.calculator android.permission.WRITE_CALENDAR
pm grant com.tcl.calculator android.permission.READ_CALL_LOG
pm grant com.tcl.calculator android.permission.WRITE_CALL_LOG
pm grant com.tcl.calculator android.permission.CAMERA
pm grant com.tcl.calculator android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.calculator android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.calculator android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.calculator android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.calculator android.permission.RECORD_AUDIO
pm grant com.tcl.calculator android.permission.READ_SMS
pm grant com.tcl.fmradio android.permission.READ_CONTACTS
pm grant com.tcl.fmradio android.permission.WRITE_CONTACTS
pm grant com.tcl.fmradio android.permission.GET_ACCOUNTS
pm grant com.tcl.fmradio android.permission.READ_PHONE_STATE
pm grant com.tcl.fmradio android.permission.CALL_PHONE
pm grant com.tcl.fmradio android.permission.READ_CALENDAR
pm grant com.tcl.fmradio android.permission.WRITE_CALENDAR
pm grant com.tcl.fmradio android.permission.READ_CALL_LOG
pm grant com.tcl.fmradio android.permission.WRITE_CALL_LOG
pm grant com.tcl.fmradio android.permission.CAMERA
pm grant com.tcl.fmradio android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.fmradio android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.fmradio android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.fmradio android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.fmradio android.permission.RECORD_AUDIO
pm grant com.tcl.fmradio android.permission.READ_SMS
pm grant com.tcl.gallery android.permission.READ_CONTACTS
pm grant com.tcl.gallery android.permission.WRITE_CONTACTS
pm grant com.tcl.gallery android.permission.GET_ACCOUNTS
pm grant com.tcl.gallery android.permission.READ_PHONE_STATE
pm grant com.tcl.gallery android.permission.CALL_PHONE
pm grant com.tcl.gallery android.permission.READ_CALENDAR
pm grant com.tcl.gallery android.permission.WRITE_CALENDAR
pm grant com.tcl.gallery android.permission.READ_CALL_LOG
pm grant com.tcl.gallery android.permission.WRITE_CALL_LOG
pm grant com.tcl.gallery android.permission.CAMERA
pm grant com.tcl.gallery android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.gallery android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.gallery android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.gallery android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.gallery android.permission.RECORD_AUDIO
pm grant com.tcl.gallery android.permission.READ_SMS
pm grant com.tcl.usercare android.permission.READ_CONTACTS
pm grant com.tcl.usercare android.permission.WRITE_CONTACTS
pm grant com.tcl.usercare android.permission.GET_ACCOUNTS
pm grant com.tcl.usercare android.permission.READ_PHONE_STATE
pm grant com.tcl.usercare android.permission.CALL_PHONE
pm grant com.tcl.usercare android.permission.READ_CALENDAR
pm grant com.tcl.usercare android.permission.WRITE_CALENDAR
pm grant com.tcl.usercare android.permission.READ_CALL_LOG
pm grant com.tcl.usercare android.permission.WRITE_CALL_LOG
pm grant com.tcl.usercare android.permission.CAMERA
pm grant com.tcl.usercare android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.usercare android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.usercare android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.usercare android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.usercare android.permission.RECORD_AUDIO
pm grant com.tcl.usercare android.permission.READ_SMS
pm grant com.facebook.lite android.permission.READ_CONTACTS
pm grant com.facebook.lite android.permission.WRITE_CONTACTS
pm grant com.facebook.lite android.permission.GET_ACCOUNTS
pm grant com.facebook.lite android.permission.READ_PHONE_STATE
pm grant com.facebook.lite android.permission.CALL_PHONE
pm grant com.facebook.lite android.permission.READ_CALENDAR
pm grant com.facebook.lite android.permission.WRITE_CALENDAR
pm grant com.facebook.lite android.permission.READ_CALL_LOG
pm grant com.facebook.lite android.permission.WRITE_CALL_LOG
pm grant com.facebook.lite android.permission.CAMERA
pm grant com.facebook.lite android.permission.ACCESS_FINE_LOCATION
pm grant com.facebook.lite android.permission.ACCESS_COARSE_LOCATION
pm grant com.facebook.lite android.permission.READ_EXTERNAL_STORAGE
pm grant com.facebook.lite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.facebook.lite android.permission.RECORD_AUDIO
pm grant com.facebook.lite android.permission.READ_SMS
sh /data/local/tmp/Mute.sh&